server:
  port: 12898
spring:
  application:
    name: yiki-oauth2
  cloud:
    nacos:
      discovery:
        server-addr: http://139.159.134.136:8848
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 1
