server:
  port: 12888

spring:
  application:
    name: yiki-gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://139.159.134.136:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: doc-manage
          uri: lb://yiki-doc-manage
          predicates:
            - Path=/yiki-doc-manage/**
          filters:
            - StripPrefix=1
        - id: oauth2
          uri: lb://yiki-oauth2
          predicates:
            - Path=/yiki-oauth2/**
          filters:
            - StripPrefix=1
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 1